### PR TITLE
handle multiple remotes

### LINKED ISSUE #3: invalid URLs generated when multiple remotes are present
Inside [this repo](https://github.com/RHElements/rhelements), the following...

```vim
    let l:git_remote = system("cat .git/config | grep \"url\" | sed \"s/url.*://g\" | awk '{print \"https://github.com/\", $0}' | tr -d '[:blank:]' | sed \"s/\.git$//g\" | tr -d '\n'")
```

returns this, a concatenation of all the remotes' URLs:

```
https://github.com/RHElements/rhelementshttps://github.com/kylebuch8/rhelements
```

### PR DESCRIPTION
**Pull request by mwcz**
fixes #3

### CODE REVIEW

**Comment by mopp** [comment]
I also faced the #3 .
Thanks @mwcz 😄 

I tried using the fixed command in this PR.
The issue is caused still however,

Here is the steps to reproduce them.

My environment
```
:version
NVIM v0.3.2-69-ga2253744c
Build type: Release
LuaJIT 2.0.5

macOS Sierra 10.12.6
```

```console
git clone https://github.com/prakashdanish/vim-githubinator.git
cd vim-githubinator/
nvim -u NONE
```
Execute in neovim the snippet (copied from this PR)
```vim
:echo system("cat .git/config | grep \"remote \\\"origin\\\"\" -A1 | grep \"url\" | sed \"s/url.*://g\" | awk '{print \"https://github.com/\", $0}' | tr -d '[:blank:]' | sed \"s/\.git$//g\" | tr -d '\n'")
```
It outputs `https://github.com///github.com/prakashdanish/vim-githubinator`.
The output has to be `https://github.com/prakashdanish/vim-githubinator`.

Fortunately I have a snippet to get the URL in my `.gitconfig`.
https://github.com/mopp/dotfiles/blob/master/.gitconfig#L27
```vim
:echo system("git config remote.origin.url | sed -Ee 's!(git@|git://|ssh://)!https://!' -e 's!:([^/])!/\\1!'") 
```

I want you to use the way. (CC: @prakashdanish )
This way also solves #5.
Further, it supports GHE (Github Enterprise) such as `http://github.my_company.com/nice_project/good_product.git`

Thanks.

P.S.
To support multiple remote (for instance `origin` and `upstream`), the `remote.XXX.url` part need to be modified.
```
let remote = 'upstream'
:echo system("git config remote." . remote .  ".url | sed -Ee 's!(git@|git://|ssh://)!https://!' -e 's!:([^/])!/\\1!'") 
```

**Comment by moopet** [comment]
A sensible approach might be to use origin as a default but allow overriding in a user's config like

    let g:githubinator_remote = 'upstream'

**Comment by mopp** [comment]
@moopet It is better to change the remote name dynamically
For example, `GithubInatorCopy some_remote_name`.

**Comment by danishprakash** [comment]
@mwcz  thanks for the pr, this seems like an interesting use case.

@mopp that works great but I'm still figuring how that sed script actually works, given I'm not a sed expert.
```vim
:echo system("git config remote." . remote .  ".url | sed -Ee 's!(git@|git://|ssh://)!https://!' -e 's!:([^/])!/\\1!'") 
```

@mopp @moopet I'd rather have the remote set in my .vimrc since I personally don't hop around remotes much. Because if we do `GithubInatorCopy some_remote_name.` then it'll be required of the user to set the remote every time he/she starts vim, correct me if I'm wrong here. But if it makes sense to have it set dynamically then why not.

**Comment by mopp** [comment]
@prakashdanish I'm not so familiar with `sed` (usually I use vim 😃)

Here is explanation.
There are 3 types of git remote URL we can obtain using`git config remote.origin.url`
1. git@github.com:mopp/hoge.vim.git
2. https://github.com/mopp/dotfiles.git
3. ssh://user@host:1234/srv/git/example (I don't remember why I added this case...)

This part `s!(git@|git://|ssh://)!https://!` replaces the URL scheme to `https://`
These are 
1.  https://github.com:mopp/hoge.vim.git
2. https://github.com/mopp/dotfiles.git (not changed)
3. https://user@host:1234/srv/git/example

The rest part of sed is to replaces the `:`  for case 1.
1.  https://github.com/mopp/hoge.vim.git
2. https://github.com/mopp/dotfiles.git (not changed)
3. https://user@host/1234/srv/git/example (oh, this is bug...)

That's all.
The ssh part might be removed because it is rare case I think.

> it'll be required of the user to set the remote every time he/she starts vim

Sorry for missing description.
The default argument will be `origin` if `GithubInatorCopy` is defined.

**Comment by mwcz** [comment]
I also wound up using `git config` instead of `cat .git/config` in order to solve #4, but went down a rabbit hole and had to abandon it for sake of time.

I like @moopet's suggestion of:

```vim
let g:githubinator_remote = 'upstream'
```

It allows users to express their global preference for naming remotes in their vimrc, or on a per-project basis with [vim-localvimrc](https://github.com/embear/vim-localvimrc).

I'm thinking this PR should probably be closed and a new one opened based on @mopp and @moopet's (lol) excellent suggestions.

**Comment by mopp** [comment]
> It allows users to express their global preference for naming remotes in their vimrc, or on a per-project basis with vim-localvimrc.

I figured out that the default remote is defined by `g:githubinator_remote`.

I'm ok for @mwcz to continue this PR based on my snippet.
New PR is also no problem !

**Comment by mopp** [comment]
Hi !
This PR seems to be frozen.

@prakashdanish Could I create new PR ?

**Comment by mwcz** [comment]
Yes, sorry, I haven't had time to get back to it.  A new PR would be great!

**Comment by mopp** [comment]
@mwcz OK, I will send new one.
Thanks for your work !

**Comment by danishprakash** [comment]
@mopp definitely go ahead!

**Comment by mopp** [comment]
I have worked on the PR #8.
So this PR should be closed.

**Comment by mwcz** [comment]
Thanks @mopp !

**Pull request closed without merging**
